version: '3'

services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./python_nctu_cancer:/app
      - ./log:/var/log/nginx
    depends_on:
      - web
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    restart: always
    expose:
      - "80"
    volumes:
      - .:/app