version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    expose:
      - "8000"
    volumes:
      - .:/app
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
